# fly.toml app configuration file generated for autowood on 2024-11-05T19:59:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'autowood'
primary_region = 'waw'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[mounts]
source="autowooddb"
destination="/AutoWood_Backend"

[processes]
  app = 'gunicorn --bind :8000 --workers 2 AutoWood_Backend.wsgi'
  celery = 'celery -A AutoWood_Backend worker --loglevel=INFO'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
