# Generated by Django 5.0 on 2025-06-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_accesories_cost_newproject_accessories_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paints',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
